export default {
  NETFLIX: 'Netflix',
  SEARCH_PLACEHOLDER: 'Titles',
  API_BASE_URL: 'http://www.omdbapi.com/',
  API_KEY: '236ef7aa',
  REQUEST_TIME_OUT: 10000,
  MOVIE: 'movie',
  SERIES: 'series',
  EPISODE: 'episode',
  MAN: 'man',
  GUN: 'gun',
  POPULAR_ON_NETFLIX: 'Popular on Netflix',
  CLASSIC_FILM: 'Classic Film',
  TV_SERIES: 'TV Series',
  NA: 'N/A',
  RELEASE_DATE: 'Release Date',
  GENRE: 'Genre',
  DIRECTOR: 'Director',
  ACTORS: 'Actors',
  TOTAL_REVENUE: 'Total Revenue',
  MOVIE_NOT_FOUND: 'No movie available',
  SEARCH_DELAY: 500,
  MINIMUM_SEARCH_KEYWORD: 3
}
